#!/usr/bin/env node
// Which 1° cells of the Earth are sea, for layers that live only on the
// oceans (plankton). Built locally from Natural Earth land (1:110m, via the
// world-atlas package already in the project): no network requests at all.
//
// Output: src/core/data/ocean-mask.ts, one bit per cell (1 = sea), rows from
// 90°N southward, columns from 180°W eastward, cell centres at half degrees,
// packed as base64.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { geoContains } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "..", "src", "core", "data", "ocean-mask.ts");

const topo = JSON.parse(readFileSync(require.resolve("world-atlas/land-110m.json"), "utf8"));
const land = feature(topo, topo.objects.land);

const W = 360;
const H = 180;
const bits = new Uint8Array(Math.ceil((W * H) / 8));
let sea = 0;
for (let row = 0; row < H; row++) {
  const lat = 89.5 - row;
  for (let col = 0; col < W; col++) {
    const lng = -179.5 + col;
    if (!geoContains(land, [lng, lat])) {
      const i = row * W + col;
      bits[i >> 3] |= 1 << (i & 7);
      sea++;
    }
  }
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by scripts/earth/ocean-mask.mjs from Natural Earth land (1:110m, public domain,
// via world-atlas, ISC). Do not edit. One bit per 1° cell, 1 = sea; rows from 90°N, columns
// from 180°W; cell centres at half degrees.
export const OCEAN_MASK = { width: ${W}, height: ${H}, bits: ${JSON.stringify(Buffer.from(bits).toString("base64"))} };
`,
);
console.log(`Wrote ${OUT}: ${sea} of ${W * H} cells are sea (${Math.round((100 * sea) / (W * H))}%).`);
